### ISSUE TITLE
Global tags support

### ISSUE THREAD

**Issue by SukharevAndrey** [prometheus-net/prometheus-net#116] opened 2019-01-09 12:03 UTC
It would be great to have global tags support such as machine name, environment and so on with ability to change them.

**Comment by sandersaares** [comment] 2019-01-09 12:09
This type of feature has occasionally been discussed in various Prometheus discussion groups and the conclusions I have seen appear to be that this type of tag is better defined in the Prometheus database scrape configuration, instead of being provided by the exporter.

I am not strictly opposed to such a feature but I do not wish to deviate from what other libraries are doing, nor from best practices.

* Is there another Prometheus library you know of that implement such a feature?
* Have you raised the topic in [prometheus-users](https://groups.google.com/forum/#!forum/prometheus-users) and gotten feedback that this is a good approach?

Either of the above would be a good signal that this type of feature would be sensible to implement.

**Comment by SukharevAndrey** [comment] 2019-01-09 12:16
Thank you for the quick answer.
I investigated usage of AppMetrics (https://github.com/AppMetrics) library, but the author seems to have abandoned it, and it has major problems that are not solved in months.
Concept of the library is great, and I found global tags from it quite useful. Details can be found here: https://www.app-metrics.io/getting-started/fundamentals/tagging-organizing/
Currently I'm using thin wrapper of prometheus-net where I have global tags, but it would be great to have the functionality in core.

**Comment by sandersaares** [comment] 2019-01-30 11:41
Wouldn't just the `labels` field in Prometheus configuration do this?

For example, in case of `static_config`:

```
# Labels assigned to all metrics scraped from the targets.
labels:
  [ <labelname>: <labelvalue> ... ]
```

I imagine there are also equivalents for other target source types.

Specifying these in Prometheus config seems to be the best practice and seems to be what other Prometheus libraries implement. I wish to take a conservative stand here and not be too innovative in this library, to stick to what is the known behavior. As such, I will close this issue - there is an alternative approach and the current lack of this feature in the library is by design.

If you think this is not right, please post a thread on the [prometheus-users](https://groups.google.com/forum/#!forum/prometheus-users) mailing list. If you can get support for your global tags suggestion in there, it would go a long way towards changing my mind about this.

**Closed by sandersaares** 2019-01-30 11:41 UTC
