### ISSUE TITLE
Installing with .net 4.6.1

### ISSUE THREAD

**Issue by MartinBodocky** [prometheus-net/prometheus-net#95] opened 2018-09-13 11:34 UTC
Hi guys,

I am using older operationg system Windows Server 2008 R2 with installed .Net 4.6.1, VS 2015 Update 3, and I have run into following issue:

Attempting to gather dependency information for package 'prometheus-net.2.1.2' with respect to project 'ConsoleApplication1', targeting '.NETFramework,Version=v4.6.1'
Attempting to resolve dependencies for package 'prometheus-net.2.1.2' with DependencyBehavior 'Lowest'
Resolving actions to install package 'prometheus-net.2.1.2'
Resolved actions to install package 'prometheus-net.2.1.2'
  GET https://api.nuget.org/v3-flatcontainer/protobuf-net/2.3.4/protobuf-net.2.3.4.nupkg
  OK https://api.nuget.org/v3-flatcontainer/protobuf-net/2.3.4/protobuf-net.2.3.4.nupkg 575ms
Installing protobuf-net 2.3.4.
Adding package 'protobuf-net.2.3.4' to folder 'c:\users\ha#mag\documents\visual studio 2015\Projects\ConsoleApplication1\packages'
Added package 'protobuf-net.2.3.4' to folder 'c:\users\ha#mag\documents\visual studio 2015\Projects\ConsoleApplication1\packages'
Added package 'protobuf-net.2.3.4' to 'packages.config'
Successfully installed 'protobuf-net 2.3.4' to ConsoleApplication1
  GET https://api.nuget.org/v3-flatcontainer/prometheus-net/2.1.2/prometheus-net.2.1.2.nupkg
  OK https://api.nuget.org/v3-flatcontainer/prometheus-net/2.1.2/prometheus-net.2.1.2.nupkg 581ms
Installing prometheus-net 2.1.2.
Install failed. Rolling back...
Package 'prometheus-net.2.1.2 : protobuf-net [2.3.4, )' does not exist in project 'ConsoleApplication1'
Removed package 'protobuf-net.2.3.4' from 'packages.config'
Package 'prometheus-net.2.1.2 : protobuf-net [2.3.4, )' does not exist in folder 'c:\users\ha#mag\documents\visual studio 2015\Projects\ConsoleApplication1\packages'
Removing package 'protobuf-net.2.3.4' from folder 'c:\users\ha#mag\documents\visual studio 2015\Projects\ConsoleApplication1\packages'
Removed package 'protobuf-net.2.3.4' from folder 'c:\users\ha#mag\documents\visual studio 2015\Projects\ConsoleApplication1\packages'
Could not install package 'prometheus-net 2.1.2'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
========== Finished ==========

I hope you can help me with that.

Thank you in advance,

Martin Bodocky

**Comment by sandersaares** [comment] 2018-09-25 06:56
I am unable to reproduce this on the latest version of Visual Studio. I am therefore closing this issue, as it is likely caused by an older version of the tooling.

I recommend you upgrade your tooling (Visual Studio and/or NuGet) to the latest published versions. The .NET tooling went through many difficult years and had many problems in recent history when working with .NET Standard libraries. I would not be surprised at all by the fact that older versions of Visual Studio have issues.

As a workaround, you might try using a stand-alone install of nuget.exe from the command line, instead of adding the package via Visual Studio.

**Closed by sandersaares** 2018-09-25 06:56 UTC
