### ISSUE TITLE
Support for .net core 3.0

### ISSUE THREAD

**Issue by robertmircea** [prometheus-net/prometheus-net#156] opened 2019-08-23 21:25 UTC
How do I use prometheus-net.AspNetCore with .Net Core 3.0 when using  app.UseEndpoints?

If I insert in Startup.Configure, app.UseHttpMetrics() it seems it does not catches controller and action names.

**Comment by RagingKore** [comment] 2019-09-02 10:09
I'm more than willing to contribute with the first iteration for a full .Net Core 3.0 implementation since everything is sealed and internal and changing certain components is impossible.

Is this something that would be of interest @sandersaares?

**Comment by sandersaares** [comment] 2019-09-24 11:45
This library is compatible with .NET Core 3.0 and ASP.NET Core 3.0 in so far as I know.

When I insert the required configuration in `Startup.Configure()`, I get the expected metrics output.

```csharp
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            app.UseMetricServer();
            app.UseHttpMetrics();
```

This is using the default ASP.NET Core 3.0 MVC project template in latest Visual Studio.

The output correctly contains the controller and action:

![image](https://user-images.githubusercontent.com/9914262/65508913-f7501180-ded9-11e9-8567-ea9ffdd356da.png)

If this does not match what you are seeing, please provide details on how to reproduce the issue.

**Comment by robertmircea** [comment] 2019-09-25 20:21
For me is not the same. Controller name and action name are missing. 
app.UseHttpMetrics() is first line in Startup.Configure() method.

```
# HELP http_request_duration_seconds The duration of HTTP requests processed by an ASP.NET Core application.
# TYPE http_request_duration_seconds histogram
http_request_duration_seconds_sum{code="200",method="GET",controller="",action=""} 0.0624808
http_request_duration_seconds_count{code="200",method="GET",controller="",action=""} 3
http_request_duration_seconds_bucket{code="200",method="GET",controller="",action="",le="0.001"} 0
http_request_duration_seconds_bucket{code="200",method="GET",controller="",action="",le="0.002"} 0
http_request_duration_seconds_bucket{code="200",method="GET",controller="",action="",le="0.004"} 0
http_request_duration_seconds_bucket{code="200",method="GET",controller="",action="",le="0.008"} 0
```

**Comment by sandersaares** [comment] 2019-09-25 20:49
Please post a full ASP.NET Core project (e.g. as a GitHub repository) that I can use to reproduce and investigate this issue.

**Comment by sandersaares** [comment] 2019-10-11 09:56
I will close this due to timeout. If you still have issues, please post an entire project that demonstrates the issue.

**Closed by sandersaares** 2019-10-11 09:56 UTC
Labels: waiting for author
